### ISSUE TITLE
SampleToolTip

### ISSUE THREAD

**Issue by AlexanderPavlenko** [Frooxius/NeosSampleLibrary#7]
I guess, it's already inside 
the NeosVR/Libraries/NeosSampleLibrary.dll, but how to spawn it?

**Comment by Frooxius** [comment]
You can do that by simply creating empty object and attaching the tooltip component on it. You could also open the Scratchspace world template which includes all the tooltips pre-spawned.

**Comment by AlexanderPavlenko** [comment]
Thanks! I just tried both ways but didn't find it there. Steam "verify integrity of game files" says all is valid.
